#!/usr/bin/env bash

DIR="$(cd -P "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
source "${DIR}/ltoggle-common"

wmctrl -l
read -p "id of window > " LTOGGLE_CAPTURE_ID_TEMP
echo "${LTOGGLE_CAPTURE_ID_TEMP}" > "${DIR}/${IDPREFIX}-${1}"
unset LTOGGLE_CAPTURE_ID_TEMP

