#!/usr/bin/env bash

DIR="$(cd -P "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
source "${DIR}/ltoggle-common"

xdotool click 1 | xwininfo | grep -oP 'Window id: \K\w+' 2> "/dev/null" 1> "${DIR}/${IDPREFIX}-${1}"

