#!/usr/bin/env bash

DIR="$(cd -P "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd)"
source "${DIR}/ltoggle-common"


__redirnullbg ${LTOGGLE_MAP["${1}|cmd"]}
__waitopen "${LTOGGLE_MAP["${1}|wait"]}"
__recordactivewinid "${1}"

